---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

This is a line from RStudio
Matthew added this line from Rustdio
Grant added this line from RStudio.

Step 12.1: 

Croix: I had all prerequisites set up already, no further work.
Matthew: Had to install git and do the global configs, otherwise all was fine.
Grant: This step was easy since I already completed the prerequisite.

Step 12.3: 

Croix: This process went smoothly getting into the environment.
Matt: Didn't have git installed initially, but otherwise creation went fine.
Grant: It was easy to set up the repository, it was important to remember where I saved the project locally.

Step 12.4:

Croix: Committing worked perfect, followed instructions.
Matt: Committing worked fine for me.
Grant: This step went fine until I had to commit, I had problems signing my account in with git.

Step 12.5:

Croix: The push worked perfect, no issues.
I skipped knitting initially, but after that I was able to push/pull to GH.
Grant: This step went smooth after I figured out that I need to commit before I push.

Step 12.6:
Grant: I added my line to the wrong README file at first but after I figured that out it went well.
Croix: Changes were shown as expected. Complete process went smoothly.
Went well I learned the correct order of how to pull/edit/knit/commit/push.


